edit model video
softkesla/homework pull request #30
Opened 2023-01-09 02:42 UTC by nutanuthep

edit model video by using **filestoreage** and **storeage**

2023-01-09 03:17 UTC, krisadatreg approved these changes

2023-01-09 03:24 UTC, jimmykesla requested changes

2023-01-09 03:24 UTC, jimmykesla commented on .json_models/channel.json
> +    "__path": "/packages/post_repository/lib/src/post_page/model",
use models instead of model folder

2023-01-09 03:24 UTC, jimmykesla commented on .json_models/media.json
> +    "__path": "/packages/post_repository/lib/src/post_page/model",
models folder name

2023-01-09 03:24 UTC, jimmykesla commented on .json_models/post.json
> +}
new line

2023-01-12 08:13 UTC, jimmykesla approved these changes

2023-01-12 08:13 UTC, merged